<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        City::create(['province_id' => '1', 'city_id' => '32', 'title' => 'Bangli']);
        City::create(['province_id' => '1', 'city_id' => '94', 'title' => 'Buleleng']);
        City::create(['province_id' => '1', 'city_id' => '114', 'title' => 'Denpasar']);
        City::create(['province_id' => '1', 'city_id' => '128', 'title' => 'Gianyar']);
        City::create(['province_id' => '1', 'city_id' => '161', 'title' => 'Jembrana']);
        City::create(['province_id' => '1', 'city_id' => '170', 'title' => 'Karangasem']);
        City::create(['province_id' => '1', 'city_id' => '197', 'title' => 'Klungkung']);
        City::create(['province_id' => '1', 'city_id' => '447', 'title' => 'Tabanan']);
        City::create(['province_id' => '2', 'city_id' => '27', 'title' => 'Bangka']);
        City::create(['province_id' => '2', 'city_id' => '28', 'title' => 'Bangka Barat']);
        City::create(['province_id' => '2', 'city_id' => '29', 'title' => 'Bangka Selatan']);
        City::create(['province_id' => '2', 'city_id' => '30', 'title' => 'Bangka Tengah']);
        City::create(['province_id' => '2', 'city_id' => '56', 'title' => 'Belitung']);
        City::create(['province_id' => '2', 'city_id' => '57', 'title' => 'Belitung Timur']);
        City::create(['province_id' => '2', 'city_id' => '334', 'title' => 'Pangkal Pinang']);
        City::create(['province_id' => '3', 'city_id' => '106', 'title' => 'Cilegon']);
        City::create(['province_id' => '3', 'city_id' => '232', 'title' => 'Lebak']);
        City::create(['province_id' => '3', 'city_id' => '331', 'title' => 'Pandeglang']);
        City::create(['province_id' => '3', 'city_id' => '402', 'title' => 'Serang']);
        City::create(['province_id' => '3', 'city_id' => '403', 'title' => 'Serang']);
        City::create(['province_id' => '3', 'city_id' => '455', 'title' => 'Tangerang']);
        City::create(['province_id' => '3', 'city_id' => '456', 'title' => 'Tangerang']);
        City::create(['province_id' => '3', 'city_id' => '457', 'title' => 'Tangerang Selatan']);
        City::create(['province_id' => '4', 'city_id' => '62', 'title' => 'Bengkulu']);
        City::create(['province_id' => '4', 'city_id' => '63', 'title' => 'Bengkulu Selatan']);
        City::create(['province_id' => '4', 'city_id' => '64', 'title' => 'Bengkulu Tengah']);
        City::create(['province_id' => '4', 'city_id' => '65', 'title' => 'Bengkulu Utara']);
        City::create(['province_id' => '4', 'city_id' => '175', 'title' => 'Kaur']);
        City::create(['province_id' => '4', 'city_id' => '183', 'title' => 'Kepahiang']);
        City::create(['province_id' => '4', 'city_id' => '233', 'title' => 'Lebong']);
        City::create(['province_id' => '4', 'city_id' => '294', 'title' => 'Muko Muko']);
        City::create(['province_id' => '4', 'city_id' => '379', 'title' => 'Rejang Lebong']);
        City::create(['province_id' => '4', 'city_id' => '397', 'title' => 'Seluma']);
        City::create(['province_id' => '5', 'city_id' => '39', 'title' => 'Bantul']);
        City::create(['province_id' => '5', 'city_id' => '135', 'title' => 'Gunung Kidul']);
        City::create(['province_id' => '5', 'city_id' => '210', 'title' => 'Kulon Progo']);
        City::create(['province_id' => '5', 'city_id' => '419', 'title' => 'Sleman']);
        City::create(['province_id' => '5', 'city_id' => '501', 'title' => 'Yogyakarta']);
        City::create(['province_id' => '6', 'city_id' => '151', 'title' => 'Jakarta Barat']);
        City::create(['province_id' => '6', 'city_id' => '152', 'title' => 'Jakarta Pusat']);
        City::create(['province_id' => '6', 'city_id' => '153', 'title' => 'Jakarta Selatan']);
        City::create(['province_id' => '6', 'city_id' => '154', 'title' => 'Jakarta Timur']);
        City::create(['province_id' => '6', 'city_id' => '155', 'title' => 'Jakarta Utara']);
        City::create(['province_id' => '6', 'city_id' => '189', 'title' => 'Kepulauan Seribu']);
        City::create(['province_id' => '7', 'city_id' => '77', 'title' => 'Boalemo']);
        City::create(['province_id' => '7', 'city_id' => '88', 'title' => 'Bone Bolango']);
        City::create(['province_id' => '7', 'city_id' => '129', 'title' => 'Gorontalo']);
        City::create(['province_id' => '7', 'city_id' => '130', 'title' => 'Gorontalo']);
        City::create(['province_id' => '7', 'city_id' => '131', 'title' => 'Gorontalo Utara']);
        City::create(['province_id' => '7', 'city_id' => '361', 'title' => 'Pohuwato']);
        City::create(['province_id' => '8', 'city_id' => '50', 'title' => 'Batang Hari']);
        City::create(['province_id' => '8', 'city_id' => '97', 'title' => 'Bungo']);
        City::create(['province_id' => '8', 'city_id' => '156', 'title' => 'Jambi']);
        City::create(['province_id' => '8', 'city_id' => '194', 'title' => 'Kerinci']);
        City::create(['province_id' => '8', 'city_id' => '280', 'title' => 'Merangin']);
        City::create(['province_id' => '8', 'city_id' => '293', 'title' => 'Muaro Jambi']);
        City::create(['province_id' => '8', 'city_id' => '393', 'title' => 'Sarolangun']);
        City::create(['province_id' => '8', 'city_id' => '442', 'title' => 'Sungaipenuh']);
        City::create(['province_id' => '8', 'city_id' => '460', 'title' => 'Tanjung Jabung Barat']);
        City::create(['province_id' => '8', 'city_id' => '461', 'title' => 'Tanjung Jabung Timur']);
        City::create(['province_id' => '8', 'city_id' => '471', 'title' => 'Tebo']);
        City::create(['province_id' => '9', 'city_id' => '22', 'title' => 'Kab. Bandung']);
        City::create(['province_id' => '9', 'city_id' => '23', 'title' => 'Kota Bandung']);
        City::create(['province_id' => '9', 'city_id' => '24', 'title' => 'Bandung Barat']);
        City::create(['province_id' => '9', 'city_id' => '34', 'title' => 'Banjar']);
        City::create(['province_id' => '9', 'city_id' => '54', 'title' => 'Bekasi']);
        City::create(['province_id' => '9', 'city_id' => '55', 'title' => 'Bekasi']);
        City::create(['province_id' => '9', 'city_id' => '78', 'title' => 'Bogor']);
        City::create(['province_id' => '9', 'city_id' => '79', 'title' => 'Bogor']);
        City::create(['province_id' => '9', 'city_id' => '103', 'title' => 'Ciamis']);
        City::create(['province_id' => '9', 'city_id' => '104', 'title' => 'Cianjur']);
        City::create(['province_id' => '9', 'city_id' => '107', 'title' => 'Cimahi']);
        City::create(['province_id' => '9', 'city_id' => '108', 'title' => 'Cirebon']);
        City::create(['province_id' => '9', 'city_id' => '109', 'title' => 'Cirebon']);
        City::create(['province_id' => '9', 'city_id' => '115', 'title' => 'Depok']);
        City::create(['province_id' => '9', 'city_id' => '126', 'title' => 'Garut']);
        City::create(['province_id' => '9', 'city_id' => '149', 'title' => 'Indramayu']);
        City::create(['province_id' => '9', 'city_id' => '171', 'title' => 'Karawang']);
        City::create(['province_id' => '9', 'city_id' => '211', 'title' => 'Kuningan']);
        City::create(['province_id' => '9', 'city_id' => '252', 'title' => 'Majalengka']);
        City::create(['province_id' => '9', 'city_id' => '332', 'title' => 'Pangandaran']);
        City::create(['province_id' => '9', 'city_id' => '376', 'title' => 'Purwakarta']);
        City::create(['province_id' => '9', 'city_id' => '428', 'title' => 'Subang']);
        City::create(['province_id' => '9', 'city_id' => '430', 'title' => 'Sukabumi']);
        City::create(['province_id' => '9', 'city_id' => '431', 'title' => 'Sukabumi']);
        City::create(['province_id' => '9', 'city_id' => '440', 'title' => 'Sumedang']);
        City::create(['province_id' => '9', 'city_id' => '468', 'title' => 'Tasikmalaya']);
        City::create(['province_id' => '9', 'city_id' => '469', 'title' => 'Tasikmalaya']);
        City::create(['province_id' => '10', 'city_id' => '37', 'title' => 'Banjarnegara']);
        City::create(['province_id' => '10', 'city_id' => '41', 'title' => 'Banyumas']);
        City::create(['province_id' => '10', 'city_id' => '49', 'title' => 'Batang']);
        City::create(['province_id' => '10', 'city_id' => '76', 'title' => 'Blora']);
        City::create(['province_id' => '10', 'city_id' => '91', 'title' => 'Boyolali']);
        City::create(['province_id' => '10', 'city_id' => '92', 'title' => 'Brebes']);
        City::create(['province_id' => '10', 'city_id' => '105', 'title' => 'Cilacap']);
        City::create(['province_id' => '10', 'city_id' => '113', 'title' => 'Demak']);
        City::create(['province_id' => '10', 'city_id' => '134', 'title' => 'Grobogan']);
        City::create(['province_id' => '10', 'city_id' => '163', 'title' => 'Jepara']);
        City::create(['province_id' => '10', 'city_id' => '169', 'title' => 'Karanganyar']);
        City::create(['province_id' => '10', 'city_id' => '177', 'title' => 'Kebumen']);
        City::create(['province_id' => '10', 'city_id' => '181', 'title' => 'Kendal']);
        City::create(['province_id' => '10', 'city_id' => '196', 'title' => 'Klaten']);
        City::create(['province_id' => '10', 'city_id' => '209', 'title' => 'Kudus']);
        City::create(['province_id' => '10', 'city_id' => '249', 'title' => 'Magelang']);
        City::create(['province_id' => '10', 'city_id' => '250', 'title' => 'Magelang']);
        City::create(['province_id' => '10', 'city_id' => '344', 'title' => 'Pati']);
        City::create(['province_id' => '10', 'city_id' => '348', 'title' => 'Pekalongan']);
        City::create(['province_id' => '10', 'city_id' => '349', 'title' => 'Pekalongan']);
        City::create(['province_id' => '10', 'city_id' => '352', 'title' => 'Pemalang']);
        City::create(['province_id' => '10', 'city_id' => '375', 'title' => 'Purbalingga']);
        City::create(['province_id' => '10', 'city_id' => '377', 'title' => 'Purworejo']);
        City::create(['province_id' => '10', 'city_id' => '380', 'title' => 'Rembang']);
        City::create(['province_id' => '10', 'city_id' => '386', 'title' => 'Salatiga']);
        City::create(['province_id' => '10', 'city_id' => '398', 'title' => 'Semarang']);
        City::create(['province_id' => '10', 'city_id' => '399', 'title' => 'Semarang']);
        City::create(['province_id' => '10', 'city_id' => '427', 'title' => 'Sragen']);
        City::create(['province_id' => '10', 'city_id' => '433', 'title' => 'Sukoharjo']);
        City::create(['province_id' => '10', 'city_id' => '445', 'title' => 'Surakarta (Solo)']);
        City::create(['province_id' => '10', 'city_id' => '472', 'title' => 'Tegal']);
        City::create(['province_id' => '10', 'city_id' => '473', 'title' => 'Tegal']);
        City::create(['province_id' => '10', 'city_id' => '476', 'title' => 'Temanggung']);
        City::create(['province_id' => '10', 'city_id' => '497', 'title' => 'Wonogiri']);
        City::create(['province_id' => '10', 'city_id' => '498', 'title' => 'Wonosobo']);
        City::create(['province_id' => '11', 'city_id' => '31', 'title' => 'Bangkalan']);
        City::create(['province_id' => '11', 'city_id' => '42', 'title' => 'Banyuwangi']);
        City::create(['province_id' => '11', 'city_id' => '51', 'title' => 'Batu']);
        City::create(['province_id' => '11', 'city_id' => '74', 'title' => 'Blitar']);
        City::create(['province_id' => '11', 'city_id' => '75', 'title' => 'Blitar']);
        City::create(['province_id' => '11', 'city_id' => '80', 'title' => 'Bojonegoro']);
        City::create(['province_id' => '11', 'city_id' => '86', 'title' => 'Bondowoso']);
        City::create(['province_id' => '11', 'city_id' => '133', 'title' => 'Gresik']);
        City::create(['province_id' => '11', 'city_id' => '160', 'title' => 'Jember']);
        City::create(['province_id' => '11', 'city_id' => '164', 'title' => 'Jombang']);
        City::create(['province_id' => '11', 'city_id' => '178', 'title' => 'Kediri']);
        City::create(['province_id' => '11', 'city_id' => '179', 'title' => 'Kediri']);
        City::create(['province_id' => '11', 'city_id' => '222', 'title' => 'Lamongan']);
        City::create(['province_id' => '11', 'city_id' => '243', 'title' => 'Lumajang']);
        City::create(['province_id' => '11', 'city_id' => '247', 'title' => 'Madiun']);
        City::create(['province_id' => '11', 'city_id' => '248', 'title' => 'Madiun']);
        City::create(['province_id' => '11', 'city_id' => '251', 'title' => 'Magetan']);
        City::create(['province_id' => '11', 'city_id' => '255', 'title' => 'Malang']);
        City::create(['province_id' => '11', 'city_id' => '256', 'title' => 'Malang']);
        City::create(['province_id' => '11', 'city_id' => '289', 'title' => 'Mojokerto']);
        City::create(['province_id' => '11', 'city_id' => '290', 'title' => 'Mojokerto']);
        City::create(['province_id' => '11', 'city_id' => '305', 'title' => 'Nganjuk']);
        City::create(['province_id' => '11', 'city_id' => '306', 'title' => 'Ngawi']);
        City::create(['province_id' => '11', 'city_id' => '317', 'title' => 'Pacitan']);
        City::create(['province_id' => '11', 'city_id' => '330', 'title' => 'Pamekasan']);
        City::create(['province_id' => '11', 'city_id' => '342', 'title' => 'Pasuruan']);
        City::create(['province_id' => '11', 'city_id' => '343', 'title' => 'Pasuruan']);
        City::create(['province_id' => '11', 'city_id' => '363', 'title' => 'Ponorogo']);
        City::create(['province_id' => '11', 'city_id' => '369', 'title' => 'Probolinggo']);
        City::create(['province_id' => '11', 'city_id' => '370', 'title' => 'Probolinggo']);
        City::create(['province_id' => '11', 'city_id' => '390', 'title' => 'Sampang']);
        City::create(['province_id' => '11', 'city_id' => '409', 'title' => 'Sidoarjo']);
        City::create(['province_id' => '11', 'city_id' => '418', 'title' => 'Situbondo']);
        City::create(['province_id' => '11', 'city_id' => '441', 'title' => 'Sumenep']);
        City::create(['province_id' => '11', 'city_id' => '444', 'title' => 'Surabaya']);
        City::create(['province_id' => '11', 'city_id' => '487', 'title' => 'Trenggalek']);
        City::create(['province_id' => '11', 'city_id' => '489', 'title' => 'Tuban']);
        City::create(['province_id' => '11', 'city_id' => '492', 'title' => 'Tulungagung']);
        City::create(['province_id' => '12', 'city_id' => '61', 'title' => 'Bengkayang']);
        City::create(['province_id' => '12', 'city_id' => '168', 'title' => 'Kapuas Hulu']);
        City::create(['province_id' => '12', 'city_id' => '176', 'title' => 'Kayong Utara']);
        City::create(['province_id' => '12', 'city_id' => '195', 'title' => 'Ketapang']);
        City::create(['province_id' => '12', 'city_id' => '208', 'title' => 'Kubu Raya']);
        City::create(['province_id' => '12', 'city_id' => '228', 'title' => 'Landak']);
        City::create(['province_id' => '12', 'city_id' => '279', 'title' => 'Melawi']);
        City::create(['province_id' => '12', 'city_id' => '364', 'title' => 'Pontianak']);
        City::create(['province_id' => '12', 'city_id' => '365', 'title' => 'Pontianak']);
        City::create(['province_id' => '12', 'city_id' => '388', 'title' => 'Sambas']);
        City::create(['province_id' => '12', 'city_id' => '391', 'title' => 'Sanggau']);
        City::create(['province_id' => '12', 'city_id' => '395', 'title' => 'Sekadau']);
        City::create(['province_id' => '12', 'city_id' => '415', 'title' => 'Singkawang']);
        City::create(['province_id' => '12', 'city_id' => '417', 'title' => 'Sintang']);
        City::create(['province_id' => '13', 'city_id' => '18', 'title' => 'Balangan']);
        City::create(['province_id' => '13', 'city_id' => '33', 'title' => 'Banjar']);
        City::create(['province_id' => '13', 'city_id' => '35', 'title' => 'Banjarbaru']);
        City::create(['province_id' => '13', 'city_id' => '36', 'title' => 'Banjarmasin']);
        City::create(['province_id' => '13', 'city_id' => '43', 'title' => 'Barito Kuala']);
        City::create(['province_id' => '13', 'city_id' => '143', 'title' => 'Hulu Sungai Selatan']);
        City::create(['province_id' => '13', 'city_id' => '144', 'title' => 'Hulu Sungai Tengah']);
        City::create(['province_id' => '13', 'city_id' => '145', 'title' => 'Hulu Sungai Utara']);
        City::create(['province_id' => '13', 'city_id' => '203', 'title' => 'Kotabaru']);
        City::create(['province_id' => '13', 'city_id' => '446', 'title' => 'Tabalong']);
        City::create(['province_id' => '13', 'city_id' => '452', 'title' => 'Tanah Bumbu']);
        City::create(['province_id' => '13', 'city_id' => '454', 'title' => 'Tanah Laut']);
        City::create(['province_id' => '13', 'city_id' => '466', 'title' => 'Tapin']);
        City::create(['province_id' => '14', 'city_id' => '44', 'title' => 'Barito Selatan']);
        City::create(['province_id' => '14', 'city_id' => '45', 'title' => 'Barito Timur']);
        City::create(['province_id' => '14', 'city_id' => '46', 'title' => 'Barito Utara']);
        City::create(['province_id' => '14', 'city_id' => '136', 'title' => 'Gunung Mas']);
        City::create(['province_id' => '14', 'city_id' => '167', 'title' => 'Kapuas']);
        City::create(['province_id' => '14', 'city_id' => '174', 'title' => 'Katingan']);
        City::create(['province_id' => '14', 'city_id' => '205', 'title' => 'Kotawaringin Barat']);
        City::create(['province_id' => '14', 'city_id' => '206', 'title' => 'Kotawaringin Timur']);
        City::create(['province_id' => '14', 'city_id' => '221', 'title' => 'Lamandau']);
        City::create(['province_id' => '14', 'city_id' => '296', 'title' => 'Murung Raya']);
        City::create(['province_id' => '14', 'city_id' => '326', 'title' => 'Palangka Raya']);
        City::create(['province_id' => '14', 'city_id' => '371', 'title' => 'Pulang Pisau']);
        City::create(['province_id' => '14', 'city_id' => '405', 'title' => 'Seruyan']);
        City::create(['province_id' => '14', 'city_id' => '432', 'title' => 'Sukamara']);
        City::create(['province_id' => '15', 'city_id' => '19', 'title' => 'Balikpapan']);
        City::create(['province_id' => '15', 'city_id' => '66', 'title' => 'Berau']);
        City::create(['province_id' => '15', 'city_id' => '89', 'title' => 'Bontang']);
        City::create(['province_id' => '15', 'city_id' => '214', 'title' => 'Kutai Barat']);
        City::create(['province_id' => '15', 'city_id' => '215', 'title' => 'Kutai Kartanegara']);
        City::create(['province_id' => '15', 'city_id' => '216', 'title' => 'Kutai Timur']);
        City::create(['province_id' => '15', 'city_id' => '341', 'title' => 'Paser']);
        City::create(['province_id' => '15', 'city_id' => '354', 'title' => 'Penajam Paser Utara']);
        City::create(['province_id' => '15', 'city_id' => '387', 'title' => 'Samarinda']);
        City::create(['province_id' => '16', 'city_id' => '96', 'title' => 'Bulungan (Bulongan)']);
        City::create(['province_id' => '16', 'city_id' => '257', 'title' => 'Malinau']);
        City::create(['province_id' => '16', 'city_id' => '311', 'title' => 'Nunukan']);
        City::create(['province_id' => '16', 'city_id' => '450', 'title' => 'Tana Tidung']);
        City::create(['province_id' => '16', 'city_id' => '467', 'title' => 'Tarakan']);
        City::create(['province_id' => '17', 'city_id' => '48', 'title' => 'Batam']);
        City::create(['province_id' => '17', 'city_id' => '71', 'title' => 'Bintan']);
        City::create(['province_id' => '17', 'city_id' => '172', 'title' => 'Karimun']);
        City::create(['province_id' => '17', 'city_id' => '184', 'title' => 'Kepulauan Anambas']);
        City::create(['province_id' => '17', 'city_id' => '237', 'title' => 'Lingga']);
        City::create(['province_id' => '17', 'city_id' => '302', 'title' => 'Natuna']);
        City::create(['province_id' => '17', 'city_id' => '462', 'title' => 'Tanjung Pinang']);
        City::create(['province_id' => '18', 'city_id' => '21', 'title' => 'Bandar Lampung']);
        City::create(['province_id' => '18', 'city_id' => '223', 'title' => 'Lampung Barat']);
        City::create(['province_id' => '18', 'city_id' => '224', 'title' => 'Lampung Selatan']);
        City::create(['province_id' => '18', 'city_id' => '225', 'title' => 'Lampung Tengah']);
        City::create(['province_id' => '18', 'city_id' => '226', 'title' => 'Lampung Timur']);
        City::create(['province_id' => '18', 'city_id' => '227', 'title' => 'Lampung Utara']);
        City::create(['province_id' => '18', 'city_id' => '282', 'title' => 'Mesuji']);
        City::create(['province_id' => '18', 'city_id' => '283', 'title' => 'Metro']);
        City::create(['province_id' => '18', 'city_id' => '355', 'title' => 'Pesawaran']);
        City::create(['province_id' => '18', 'city_id' => '356', 'title' => 'Pesisir Barat']);
        City::create(['province_id' => '18', 'city_id' => '368', 'title' => 'Pringsewu']);
        City::create(['province_id' => '18', 'city_id' => '458', 'title' => 'Tanggamus']);
        City::create(['province_id' => '18', 'city_id' => '490', 'title' => 'Tulang Bawang']);
        City::create(['province_id' => '18', 'city_id' => '491', 'title' => 'Tulang Bawang Barat']);
        City::create(['province_id' => '18', 'city_id' => '496', 'title' => 'Way Kanan']);
        City::create(['province_id' => '19', 'city_id' => '14', 'title' => 'Ambon']);
        City::create(['province_id' => '19', 'city_id' => '99', 'title' => 'Buru']);
        City::create(['province_id' => '19', 'city_id' => '100', 'title' => 'Buru Selatan']);
        City::create(['province_id' => '19', 'city_id' => '185', 'title' => 'Kepulauan Aru']);
        City::create(['province_id' => '19', 'city_id' => '258', 'title' => 'Maluku Barat Daya']);
        City::create(['province_id' => '19', 'city_id' => '259', 'title' => 'Maluku Tengah']);
        City::create(['province_id' => '19', 'city_id' => '260', 'title' => 'Maluku Tenggara']);
        City::create(['province_id' => '19', 'city_id' => '261', 'title' => 'Maluku Tenggara Barat']);
        City::create(['province_id' => '19', 'city_id' => '400', 'title' => 'Seram Bagian Barat']);
        City::create(['province_id' => '19', 'city_id' => '401', 'title' => 'Seram Bagian Timur']);
        City::create(['province_id' => '19', 'city_id' => '488', 'title' => 'Tual']);
        City::create(['province_id' => '20', 'city_id' => '138', 'title' => 'Halmahera Barat']);
        City::create(['province_id' => '20', 'city_id' => '139', 'title' => 'Halmahera Selatan']);
        City::create(['province_id' => '20', 'city_id' => '140', 'title' => 'Halmahera Tengah']);
        City::create(['province_id' => '20', 'city_id' => '141', 'title' => 'Halmahera Timur']);
        City::create(['province_id' => '20', 'city_id' => '142', 'title' => 'Halmahera Utara']);
        City::create(['province_id' => '20', 'city_id' => '191', 'title' => 'Kepulauan Sula']);
        City::create(['province_id' => '20', 'city_id' => '372', 'title' => 'Pulau Morotai']);
        City::create(['province_id' => '20', 'city_id' => '477', 'title' => 'Ternate']);
        City::create(['province_id' => '20', 'city_id' => '478', 'title' => 'Tidore Kepulauan']);
        City::create(['province_id' => '21', 'city_id' => '1', 'title' => 'Aceh Barat']);
        City::create(['province_id' => '21', 'city_id' => '2', 'title' => 'Aceh Barat Daya']);
        City::create(['province_id' => '21', 'city_id' => '3', 'title' => 'Aceh Besar']);
        City::create(['province_id' => '21', 'city_id' => '4', 'title' => 'Aceh Jaya']);
        City::create(['province_id' => '21', 'city_id' => '5', 'title' => 'Aceh Selatan']);
        City::create(['province_id' => '21', 'city_id' => '6', 'title' => 'Aceh Singkil']);
        City::create(['province_id' => '21', 'city_id' => '7', 'title' => 'Aceh Tamiang']);
        City::create(['province_id' => '21', 'city_id' => '8', 'title' => 'Aceh Tengah']);
        City::create(['province_id' => '21', 'city_id' => '9', 'title' => 'Aceh Tenggara']);
        City::create(['province_id' => '21', 'city_id' => '10', 'title' => 'Aceh Timur']);
        City::create(['province_id' => '21', 'city_id' => '11', 'title' => 'Aceh Utara']);
        City::create(['province_id' => '21', 'city_id' => '20', 'title' => 'Banda Aceh']);
        City::create(['province_id' => '21', 'city_id' => '59', 'title' => 'Bener Meriah']);
        City::create(['province_id' => '21', 'city_id' => '72', 'title' => 'Bireuen']);
        City::create(['province_id' => '21', 'city_id' => '127', 'title' => 'Gayo Lues']);
        City::create(['province_id' => '21', 'city_id' => '230', 'title' => 'Langsa']);
        City::create(['province_id' => '21', 'city_id' => '235', 'title' => 'Lhokseumawe']);
        City::create(['province_id' => '21', 'city_id' => '300', 'title' => 'Nagan Raya']);
        City::create(['province_id' => '21', 'city_id' => '358', 'title' => 'Pidie']);
        City::create(['province_id' => '21', 'city_id' => '359', 'title' => 'Pidie Jaya']);
        City::create(['province_id' => '21', 'city_id' => '384', 'title' => 'Sabang']);
        City::create(['province_id' => '21', 'city_id' => '414', 'title' => 'Simeulue']);
        City::create(['province_id' => '21', 'city_id' => '429', 'title' => 'Subulussalam']);
        City::create(['province_id' => '22', 'city_id' => '68', 'title' => 'Bima']);
        City::create(['province_id' => '22', 'city_id' => '69', 'title' => 'Bima']);
        City::create(['province_id' => '22', 'city_id' => '118', 'title' => 'Dompu']);
        City::create(['province_id' => '22', 'city_id' => '238', 'title' => 'Lombok Barat']);
        City::create(['province_id' => '22', 'city_id' => '239', 'title' => 'Lombok Tengah']);
        City::create(['province_id' => '22', 'city_id' => '240', 'title' => 'Lombok Timur']);
        City::create(['province_id' => '22', 'city_id' => '241', 'title' => 'Lombok Utara']);
        City::create(['province_id' => '22', 'city_id' => '276', 'title' => 'Mataram']);
        City::create(['province_id' => '22', 'city_id' => '438', 'title' => 'Sumbawa']);
        City::create(['province_id' => '22', 'city_id' => '439', 'title' => 'Sumbawa Barat']);
        City::create(['province_id' => '23', 'city_id' => '13', 'title' => 'Alor']);
        City::create(['province_id' => '23', 'city_id' => '58', 'title' => 'Belu']);
        City::create(['province_id' => '23', 'city_id' => '122', 'title' => 'Ende']);
        City::create(['province_id' => '23', 'city_id' => '125', 'title' => 'Flores Timur']);
        City::create(['province_id' => '23', 'city_id' => '212', 'title' => 'Kupang']);
        City::create(['province_id' => '23', 'city_id' => '213', 'title' => 'Kupang']);
        City::create(['province_id' => '23', 'city_id' => '234', 'title' => 'Lembata']);
        City::create(['province_id' => '23', 'city_id' => '269', 'title' => 'Manggarai']);
        City::create(['province_id' => '23', 'city_id' => '270', 'title' => 'Manggarai Barat']);
        City::create(['province_id' => '23', 'city_id' => '271', 'title' => 'Manggarai Timur']);
        City::create(['province_id' => '23', 'city_id' => '301', 'title' => 'Nagekeo']);
        City::create(['province_id' => '23', 'city_id' => '304', 'title' => 'Ngada']);
        City::create(['province_id' => '23', 'city_id' => '383', 'title' => 'Rote Ndao']);
        City::create(['province_id' => '23', 'city_id' => '385', 'title' => 'Sabu Raijua']);
        City::create(['province_id' => '23', 'city_id' => '412', 'title' => 'Sikka']);
        City::create(['province_id' => '23', 'city_id' => '434', 'title' => 'Sumba Barat']);
        City::create(['province_id' => '23', 'city_id' => '435', 'title' => 'Sumba Barat Daya']);
        City::create(['province_id' => '23', 'city_id' => '436', 'title' => 'Sumba Tengah']);
        City::create(['province_id' => '23', 'city_id' => '437', 'title' => 'Sumba Timur']);
        City::create(['province_id' => '23', 'city_id' => '479', 'title' => 'Timor Tengah Selatan']);
        City::create(['province_id' => '23', 'city_id' => '480', 'title' => 'Timor Tengah Utara']);
        City::create(['province_id' => '24', 'city_id' => '16', 'title' => 'Asmat']);
        City::create(['province_id' => '24', 'city_id' => '67', 'title' => 'Biak Numfor']);
        City::create(['province_id' => '24', 'city_id' => '90', 'title' => 'Boven Digoel']);
        City::create(['province_id' => '24', 'city_id' => '111', 'title' => 'Deiyai (Deliyai)']);
        City::create(['province_id' => '24', 'city_id' => '117', 'title' => 'Dogiyai']);
        City::create(['province_id' => '24', 'city_id' => '150', 'title' => 'Intan Jaya']);
        City::create(['province_id' => '24', 'city_id' => '157', 'title' => 'Jayapura']);
        City::create(['province_id' => '24', 'city_id' => '158', 'title' => 'Jayapura']);
        City::create(['province_id' => '24', 'city_id' => '159', 'title' => 'Jayawijaya']);
        City::create(['province_id' => '24', 'city_id' => '180', 'title' => 'Keerom']);
        City::create(['province_id' => '24', 'city_id' => '193', 'title' => 'Kepulauan Yapen (Yapen Waropen)']);
        City::create(['province_id' => '24', 'city_id' => '231', 'title' => 'Lanny Jaya']);
        City::create(['province_id' => '24', 'city_id' => '263', 'title' => 'Mamberamo Raya']);
        City::create(['province_id' => '24', 'city_id' => '264', 'title' => 'Mamberamo Tengah']);
        City::create(['province_id' => '24', 'city_id' => '274', 'title' => 'Mappi']);
        City::create(['province_id' => '24', 'city_id' => '281', 'title' => 'Merauke']);
        City::create(['province_id' => '24', 'city_id' => '284', 'title' => 'Mimika']);
        City::create(['province_id' => '24', 'city_id' => '299', 'title' => 'Nabire']);
        City::create(['province_id' => '24', 'city_id' => '303', 'title' => 'Nduga']);
        City::create(['province_id' => '24', 'city_id' => '335', 'title' => 'Paniai']);
        City::create(['province_id' => '24', 'city_id' => '347', 'title' => 'Pegunungan Bintang']);
        City::create(['province_id' => '24', 'city_id' => '373', 'title' => 'Puncak']);
        City::create(['province_id' => '24', 'city_id' => '374', 'title' => 'Puncak Jaya']);
        City::create(['province_id' => '24', 'city_id' => '392', 'title' => 'Sarmi']);
        City::create(['province_id' => '24', 'city_id' => '443', 'title' => 'Supiori']);
        City::create(['province_id' => '24', 'city_id' => '484', 'title' => 'Tolikara']);
        City::create(['province_id' => '24', 'city_id' => '495', 'title' => 'Waropen']);
        City::create(['province_id' => '24', 'city_id' => '499', 'title' => 'Yahukimo']);
        City::create(['province_id' => '24', 'city_id' => '500', 'title' => 'Yalimo']);
        City::create(['province_id' => '25', 'city_id' => '124', 'title' => 'Fakfak']);
        City::create(['province_id' => '25', 'city_id' => '165', 'title' => 'Kaimana']);
        City::create(['province_id' => '25', 'city_id' => '272', 'title' => 'Manokwari']);
        City::create(['province_id' => '25', 'city_id' => '273', 'title' => 'Manokwari Selatan']);
        City::create(['province_id' => '25', 'city_id' => '277', 'title' => 'Maybrat']);
        City::create(['province_id' => '25', 'city_id' => '346', 'title' => 'Pegunungan Arfak']);
        City::create(['province_id' => '25', 'city_id' => '378', 'title' => 'Raja Ampat']);
        City::create(['province_id' => '25', 'city_id' => '424', 'title' => 'Sorong']);
        City::create(['province_id' => '25', 'city_id' => '425', 'title' => 'Sorong']);
        City::create(['province_id' => '25', 'city_id' => '426', 'title' => 'Sorong Selatan']);
        City::create(['province_id' => '25', 'city_id' => '449', 'title' => 'Tambrauw']);
        City::create(['province_id' => '25', 'city_id' => '474', 'title' => 'Teluk Bintuni']);
        City::create(['province_id' => '25', 'city_id' => '475', 'title' => 'Teluk Wondama']);
        City::create(['province_id' => '26', 'city_id' => '60', 'title' => 'Bengkalis']);
        City::create(['province_id' => '26', 'city_id' => '120', 'title' => 'Dumai']);
        City::create(['province_id' => '26', 'city_id' => '147', 'title' => 'Indragiri Hilir']);
        City::create(['province_id' => '26', 'city_id' => '148', 'title' => 'Indragiri Hulu']);
        City::create(['province_id' => '26', 'city_id' => '166', 'title' => 'Kampar']);
        City::create(['province_id' => '26', 'city_id' => '187', 'title' => 'Kepulauan Meranti']);
        City::create(['province_id' => '26', 'city_id' => '207', 'title' => 'Kuantan Singingi']);
        City::create(['province_id' => '26', 'city_id' => '350', 'title' => 'Pekanbaru']);
        City::create(['province_id' => '26', 'city_id' => '351', 'title' => 'Pelalawan']);
        City::create(['province_id' => '26', 'city_id' => '381', 'title' => 'Rokan Hilir']);
        City::create(['province_id' => '26', 'city_id' => '382', 'title' => 'Rokan Hulu']);
        City::create(['province_id' => '26', 'city_id' => '406', 'title' => 'Siak']);
        City::create(['province_id' => '27', 'city_id' => '253', 'title' => 'Majene']);
        City::create(['province_id' => '27', 'city_id' => '262', 'title' => 'Mamasa']);
        City::create(['province_id' => '27', 'city_id' => '265', 'title' => 'Mamuju']);
        City::create(['province_id' => '27', 'city_id' => '266', 'title' => 'Mamuju Utara']);
        City::create(['province_id' => '27', 'city_id' => '362', 'title' => 'Polewali Mandar']);
        City::create(['province_id' => '28', 'city_id' => '38', 'title' => 'Bantaeng']);
        City::create(['province_id' => '28', 'city_id' => '47', 'title' => 'Barru']);
        City::create(['province_id' => '28', 'city_id' => '87', 'title' => 'Bone']);
        City::create(['province_id' => '28', 'city_id' => '95', 'title' => 'Bulukumba']);
        City::create(['province_id' => '28', 'city_id' => '123', 'title' => 'Enrekang']);
        City::create(['province_id' => '28', 'city_id' => '132', 'title' => 'Gowa']);
        City::create(['province_id' => '28', 'city_id' => '162', 'title' => 'Jeneponto']);
        City::create(['province_id' => '28', 'city_id' => '244', 'title' => 'Luwu']);
        City::create(['province_id' => '28', 'city_id' => '245', 'title' => 'Luwu Timur']);
        City::create(['province_id' => '28', 'city_id' => '246', 'title' => 'Luwu Utara']);
        City::create(['province_id' => '28', 'city_id' => '254', 'title' => 'Makassar']);
        City::create(['province_id' => '28', 'city_id' => '275', 'title' => 'Maros']);
        City::create(['province_id' => '28', 'city_id' => '328', 'title' => 'Palopo']);
        City::create(['province_id' => '28', 'city_id' => '333', 'title' => 'Pangkajene Kepulauan']);
        City::create(['province_id' => '28', 'city_id' => '336', 'title' => 'Parepare']);
        City::create(['province_id' => '28', 'city_id' => '360', 'title' => 'Pinrang']);
        City::create(['province_id' => '28', 'city_id' => '396', 'title' => 'Selayar (Kepulauan Selayar)']);
        City::create(['province_id' => '28', 'city_id' => '408', 'title' => 'Sidenreng Rappang/Rapang']);
        City::create(['province_id' => '28', 'city_id' => '416', 'title' => 'Sinjai']);
        City::create(['province_id' => '28', 'city_id' => '423', 'title' => 'Soppeng']);
        City::create(['province_id' => '28', 'city_id' => '448', 'title' => 'Takalar']);
        City::create(['province_id' => '28', 'city_id' => '451', 'title' => 'Tana Toraja']);
        City::create(['province_id' => '28', 'city_id' => '486', 'title' => 'Toraja Utara']);
        City::create(['province_id' => '28', 'city_id' => '493', 'title' => 'Wajo']);
        City::create(['province_id' => '29', 'city_id' => '25', 'title' => 'Banggai']);
        City::create(['province_id' => '29', 'city_id' => '26', 'title' => 'Banggai Kepulauan']);
        City::create(['province_id' => '29', 'city_id' => '98', 'title' => 'Buol']);
        City::create(['province_id' => '29', 'city_id' => '119', 'title' => 'Donggala']);
        City::create(['province_id' => '29', 'city_id' => '291', 'title' => 'Morowali']);
        City::create(['province_id' => '29', 'city_id' => '329', 'title' => 'Palu']);
        City::create(['province_id' => '29', 'city_id' => '338', 'title' => 'Parigi Moutong']);
        City::create(['province_id' => '29', 'city_id' => '366', 'title' => 'Poso']);
        City::create(['province_id' => '29', 'city_id' => '410', 'title' => 'Sigi']);
        City::create(['province_id' => '29', 'city_id' => '482', 'title' => 'Tojo Una-Una']);
        City::create(['province_id' => '29', 'city_id' => '483', 'title' => 'Toli-Toli']);
        City::create(['province_id' => '30', 'city_id' => '53', 'title' => 'Bau-Bau']);
        City::create(['province_id' => '30', 'city_id' => '85', 'title' => 'Bombana']);
        City::create(['province_id' => '30', 'city_id' => '101', 'title' => 'Buton']);
        City::create(['province_id' => '30', 'city_id' => '102', 'title' => 'Buton Utara']);
        City::create(['province_id' => '30', 'city_id' => '182', 'title' => 'Kendari']);
        City::create(['province_id' => '30', 'city_id' => '198', 'title' => 'Kolaka']);
        City::create(['province_id' => '30', 'city_id' => '199', 'title' => 'Kolaka Utara']);
        City::create(['province_id' => '30', 'city_id' => '200', 'title' => 'Konawe']);
        City::create(['province_id' => '30', 'city_id' => '201', 'title' => 'Konawe Selatan']);
        City::create(['province_id' => '30', 'city_id' => '202', 'title' => 'Konawe Utara']);
        City::create(['province_id' => '30', 'city_id' => '295', 'title' => 'Muna']);
        City::create(['province_id' => '30', 'city_id' => '494', 'title' => 'Wakatobi']);
        City::create(['province_id' => '31', 'city_id' => '73', 'title' => 'Bitung']);
        City::create(['province_id' => '31', 'city_id' => '81', 'title' => 'Bolaang Mongondow (Bolmong)']);
        City::create(['province_id' => '31', 'city_id' => '82', 'title' => 'Bolaang Mongondow Selatan']);
        City::create(['province_id' => '31', 'city_id' => '83', 'title' => 'Bolaang Mongondow Timur']);
        City::create(['province_id' => '31', 'city_id' => '84', 'title' => 'Bolaang Mongondow Utara']);
        City::create(['province_id' => '31', 'city_id' => '188', 'title' => 'Kepulauan Sangihe']);
        City::create(['province_id' => '31', 'city_id' => '190', 'title' => 'Kepulauan Siau Tagulandang Biaro (Sitaro)']);
        City::create(['province_id' => '31', 'city_id' => '192', 'title' => 'Kepulauan Talaud']);
        City::create(['province_id' => '31', 'city_id' => '204', 'title' => 'Kotamobagu']);
        City::create(['province_id' => '31', 'city_id' => '267', 'title' => 'Manado']);
        City::create(['province_id' => '31', 'city_id' => '285', 'title' => 'Minahasa']);
        City::create(['province_id' => '31', 'city_id' => '286', 'title' => 'Minahasa Selatan']);
        City::create(['province_id' => '31', 'city_id' => '287', 'title' => 'Minahasa Tenggara']);
        City::create(['province_id' => '31', 'city_id' => '288', 'title' => 'Minahasa Utara']);
        City::create(['province_id' => '31', 'city_id' => '485', 'title' => 'Tomohon']);
        City::create(['province_id' => '32', 'city_id' => '12', 'title' => 'Agam']);
        City::create(['province_id' => '32', 'city_id' => '93', 'title' => 'Bukittinggi']);
        City::create(['province_id' => '32', 'city_id' => '116', 'title' => 'Dharmasraya']);
        City::create(['province_id' => '32', 'city_id' => '186', 'title' => 'Kepulauan Mentawai']);
        City::create(['province_id' => '32', 'city_id' => '236', 'title' => 'Lima Puluh Koto/Kota']);
        City::create(['province_id' => '32', 'city_id' => '318', 'title' => 'Padang']);
        City::create(['province_id' => '32', 'city_id' => '321', 'title' => 'Padang Panjang']);
        City::create(['province_id' => '32', 'city_id' => '322', 'title' => 'Padang Pariaman']);
        City::create(['province_id' => '32', 'city_id' => '337', 'title' => 'Pariaman']);
        City::create(['province_id' => '32', 'city_id' => '339', 'title' => 'Pasaman']);
        City::create(['province_id' => '32', 'city_id' => '340', 'title' => 'Pasaman Barat']);
        City::create(['province_id' => '32', 'city_id' => '345', 'title' => 'Payakumbuh']);
        City::create(['province_id' => '32', 'city_id' => '357', 'title' => 'Pesisir Selatan']);
        City::create(['province_id' => '32', 'city_id' => '394', 'title' => 'Sawah Lunto']);
        City::create(['province_id' => '32', 'city_id' => '411', 'title' => 'Sijunjung (Sawah Lunto Sijunjung)']);
        City::create(['province_id' => '32', 'city_id' => '420', 'title' => 'Solok']);
        City::create(['province_id' => '32', 'city_id' => '421', 'title' => 'Solok']);
        City::create(['province_id' => '32', 'city_id' => '422', 'title' => 'Solok Selatan']);
        City::create(['province_id' => '32', 'city_id' => '453', 'title' => 'Tanah Datar']);
        City::create(['province_id' => '33', 'city_id' => '40', 'title' => 'Banyuasin']);
        City::create(['province_id' => '33', 'city_id' => '121', 'title' => 'Empat Lawang']);
        City::create(['province_id' => '33', 'city_id' => '220', 'title' => 'Lahat']);
        City::create(['province_id' => '33', 'city_id' => '242', 'title' => 'Lubuk Linggau']);
        City::create(['province_id' => '33', 'city_id' => '292', 'title' => 'Muara Enim']);
        City::create(['province_id' => '33', 'city_id' => '297', 'title' => 'Musi Banyuasin']);
        City::create(['province_id' => '33', 'city_id' => '298', 'title' => 'Musi Rawas']);
        City::create(['province_id' => '33', 'city_id' => '312', 'title' => 'Ogan Ilir']);
        City::create(['province_id' => '33', 'city_id' => '313', 'title' => 'Ogan Komering Ilir']);
        City::create(['province_id' => '33', 'city_id' => '314', 'title' => 'Ogan Komering Ulu']);
        City::create(['province_id' => '33', 'city_id' => '315', 'title' => 'Ogan Komering Ulu Selatan']);
        City::create(['province_id' => '33', 'city_id' => '316', 'title' => 'Ogan Komering Ulu Timur']);
        City::create(['province_id' => '33', 'city_id' => '324', 'title' => 'Pagar Alam']);
        City::create(['province_id' => '33', 'city_id' => '327', 'title' => 'Palembang']);
        City::create(['province_id' => '33', 'city_id' => '367', 'title' => 'Prabumulih']);
        City::create(['province_id' => '34', 'city_id' => '15', 'title' => 'Asahan']);
        City::create(['province_id' => '34', 'city_id' => '52', 'title' => 'Batu Bara']);
        City::create(['province_id' => '34', 'city_id' => '70', 'title' => 'Binjai']);
        City::create(['province_id' => '34', 'city_id' => '110', 'title' => 'Dairi']);
        City::create(['province_id' => '34', 'city_id' => '112', 'title' => 'Deli Serdang']);
        City::create(['province_id' => '34', 'city_id' => '137', 'title' => 'Gunungsitoli']);
        City::create(['province_id' => '34', 'city_id' => '146', 'title' => 'Humbang Hasundutan']);
        City::create(['province_id' => '34', 'city_id' => '173', 'title' => 'Karo']);
        City::create(['province_id' => '34', 'city_id' => '217', 'title' => 'Labuhan Batu']);
        City::create(['province_id' => '34', 'city_id' => '218', 'title' => 'Labuhan Batu Selatan']);
        City::create(['province_id' => '34', 'city_id' => '219', 'title' => 'Labuhan Batu Utara']);
        City::create(['province_id' => '34', 'city_id' => '229', 'title' => 'Langkat']);
        City::create(['province_id' => '34', 'city_id' => '268', 'title' => 'Mandailing Natal']);
        City::create(['province_id' => '34', 'city_id' => '278', 'title' => 'Medan']);
        City::create(['province_id' => '34', 'city_id' => '307', 'title' => 'Nias']);
        City::create(['province_id' => '34', 'city_id' => '308', 'title' => 'Nias Barat']);
        City::create(['province_id' => '34', 'city_id' => '309', 'title' => 'Nias Selatan']);
        City::create(['province_id' => '34', 'city_id' => '310', 'title' => 'Nias Utara']);
        City::create(['province_id' => '34', 'city_id' => '319', 'title' => 'Padang Lawas']);
        City::create(['province_id' => '34', 'city_id' => '320', 'title' => 'Padang Lawas Utara']);
        City::create(['province_id' => '34', 'city_id' => '323', 'title' => 'Padang Sidempuan']);
        City::create(['province_id' => '34', 'city_id' => '325', 'title' => 'Pakpak Bharat']);
        City::create(['province_id' => '34', 'city_id' => '353', 'title' => 'Pematang Siantar']);
        City::create(['province_id' => '34', 'city_id' => '389', 'title' => 'Samosir']);
        City::create(['province_id' => '34', 'city_id' => '404', 'title' => 'Serdang Bedagai']);
        City::create(['province_id' => '34', 'city_id' => '407', 'title' => 'Sibolga']);
        City::create(['province_id' => '34', 'city_id' => '413', 'title' => 'Simalungun']);
        City::create(['province_id' => '34', 'city_id' => '459', 'title' => 'Tanjung Balai']);
        City::create(['province_id' => '34', 'city_id' => '463', 'title' => 'Tapanuli Selatan']);
        City::create(['province_id' => '34', 'city_id' => '464', 'title' => 'Tapanuli Tengah']);
        City::create(['province_id' => '34', 'city_id' => '465', 'title' => 'Tapanuli Utara']);
        City::create(['province_id' => '34', 'city_id' => '470', 'title' => 'Tebing Tinggi']);
        City::create(['province_id' => '34', 'city_id' => '481', 'title' => 'Toba Samosir']);
    }
}
